<a href="https://colab.research.google.com/github/Anotherbig/MyPython/blob/master/%E5%88%B6%E5%BE%A1%E6%A7%8B%E6%96%87.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
money = 8000

In [ ]:
if money >= 2000:
  print('映画館に行きます')
else:
  print('eigakan')

映画館に行きます


In [ ]:
if money >= 8000:
  print('`Disney lands')
elif money >= 2000:
    print('eigakan')
else:
    print('no where')

`Disney lands


In [ ]:
names = ['imanisi','sato','mandokoro','aa','bb']

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
len(names)

5

In [ ]:
for i in range(len(names)):
  print(names[i]+'san')

imanisisan
satosan
mandokorosan
aasan
bbsan


In [ ]:
sum = 0
for num in range(20):
  sum += (num +1)
print(sum)

210


In [ ]:
def say_hello2(name):
 print(name+'hello')

In [ ]:
say_hello2('imanishi')

imanishihello


In [ ]:
class person:
   def __init__(self,name,nationality,age):
     self.name = name
     self.nationality = nationality
     self.age = age

   def say_hello(self,name):
     print('konnitiha{}san'.format(name,self.name))

In [ ]:
imanishi = person('`imanishi','nihon',25)

In [ ]:
imanishi.age

25

In [ ]:
imanishi.say_hello('sato')

konnitihasatosan


In [ ]:
#三角形の面積
def calc_tri(base,height):
  return base*height*0.5

In [ ]:
base = 10
height = 5

result

In [ ]:
 from google.colab import drive
 drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path = 'sample_date/REDME.md'

In [ ]:
f = open(path,'w')

FileNotFoundError: ignored

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
x.shape

(3,)

In [ ]:
x.ndim

1

In [ ]:
y = np.array([
  [1,2,3], 
  [4,5,6], 
  [7,8,9]          
])

In [ ]:
y.shape

(3, 3)

In [ ]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y.mean()

5.0

In [ ]:
y.mean(axis=1)

array([2., 5., 8.])

In [ ]:
y.var()

6.666666666666667

In [ ]:
y.std()

2.581988897471611

In [ ]:
X = np.array([
  [2,3],
  [1,5],
  [3,1]            
])
X

array([[2, 3],
       [1, 5],
       [3, 1]])

In [ ]:
X.T

array([[2, 1, 3],
       [3, 5, 1]])

In [ ]:
np.dot(X,X.T)

array([[13, 17,  9],
       [17, 26,  8],
       [ 9,  8, 10]])

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [ ]:
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0
3    -118.36     33.82  ...         6.1359            330000.0
4    -119.67     36.33  ...         2.9375             81700.0

[5 rows x 9 columns]

In [ ]:
df.tail()

longitude  latitude  ...  median_income  median_house_value
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[5 rows x 9 columns]